# Copied from https://github.com/tydi-lang/tydi for now
[project]
name = "tydi-intern"
version = "0.0.0"
edition = "2018"
publish = false
description = "Intern support for Tydi"

[dependencies]
salsa = "0.16.1"
