# Copied from https://github.com/tydi-lang/tydi for now
[project]
name = "tydi-common"
version = "0.0.0"
edition = "2021"
publish = false
description = "Common traits and functions for use in Tydi crates"

[dependencies]
log = "0.4.14"
uncased = "0.9.7"